"""create initial tables with schema

Revision ID: d2890936a536
Revises: 
Create Date: 2024-07-13 16:25:15.419891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2890936a536'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_table('ethnicity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_table('gender',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_table('profession',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test'
    )
    op.create_table('employee',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('ethnicity_id', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('md5', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['test.agency.id'], ),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['test.ethnicity.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['test.gender.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['test.profession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('md5'),
    schema='test'
    )
    op.drop_table('profession', schema='your_schema_name')
    op.drop_table('ethnicity', schema='your_schema_name')
    op.drop_table('agency', schema='your_schema_name')
    op.drop_table('gender', schema='your_schema_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gender_pkey'),
    sa.UniqueConstraint('name', name='gender_name_key'),
    schema='your_schema_name'
    )
    op.create_table('agency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='agency_pkey'),
    sa.UniqueConstraint('name', name='agency_name_key'),
    schema='your_schema_name'
    )
    op.create_table('ethnicity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ethnicity_pkey'),
    sa.UniqueConstraint('name', name='ethnicity_name_key'),
    schema='your_schema_name'
    )
    op.create_table('profession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='profession_pkey'),
    sa.UniqueConstraint('name', name='profession_name_key'),
    schema='your_schema_name'
    )
    op.drop_table('employee', schema='test')
    op.drop_table('profession', schema='test')
    op.drop_table('gender', schema='test')
    op.drop_table('ethnicity', schema='test')
    op.drop_table('agency', schema='test')
    # ### end Alembic commands ###
